### ISSUE TITLE
is the documentation about the configuration file wrong?

### ISSUE THREAD

**Issue by gabrielperales** [ABuffSeagull/parcel-plugin-prerender#14]
Docs says the configuration file should look like:

```
{
  "prerender": {
    "routes": ["/", "/about"],
    "rendererConfig": {
      "renderAfterDocumentEvent": "prerender-trigger"
    }
  }
}
```

but if I create a `.prerenderrc` like that it is not getting the routes array, instead it should look like:

```
{
    "routes": ["/", "/about"],
    "rendererConfig": {
      "renderAfterDocumentEvent": "prerender-trigger"
    }
}
```

I couldn't test if it works in the first way with a `prerender.config.js` it is giving me an error too.

**Comment by ABuffSeagull** [comment]
Ah yeah, it's a bit confusing, I'll try to clean it up. 

The second one is correct in a separate file, but the first one would be if it were in the `package.json`.
Thanks for pointing this out!

As for the `prerender.config.js`, as per [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), you need to export a JS object. Basically just sticking a `module.exports = ` before your second example, if I understand the docs correctly.
