### ISSUE TITLE
Auto-generate routes

### ISSUE THREAD

**Issue by konsumer** [ABuffSeagull/parcel-plugin-prerender#20]
I often have some definitive way to get a list of routes from my app, like an import that defines my router/menu/content in react, for example. If there is interest, I'd be happy to make a PR to dynamically create routes.

It would be cool if I could tell parcel-plugin-prerender to import some file in parcel-space, then get a list of routes in a promise-returning (so I can do async calls) function. Here is an example that uses parcel-plugin-markdown-string to import a bunch of markdown files with front-matter:

**package.json:**
```json
{
  "prerender": {
   "dynamicRoutes": "src/dynamicRoutes.js",
    "rendererConfig": {
      "renderAfterDocumentEvent": "prerender-trigger"
    }
  }
}
```

**src/dynamicRoutes.js:**
```js
import fm from 'front-matter'
import rawArticles from '../articles/*.md'

export const routes = async (builder) => {
  return Object.keys(rawArticles).map(name => {
    const article = fm(rawArticles[name])
    return `/${article.attributes.slug || name}`
  })
}
```

Currently, I can work around this by running a script to generate `.prerenderrc` before I do the build, but it'd be cool if it was integrated.

**Comment by konsumer** [comment]
Here is an example I am using currently, if anyone is curious:

**src/prerender.js:**
```js
import { writeFileSync } from 'fs'
import articles from './articles'

const routes = articles
  .filter(article => article.attributes.url.slice(0, 4) !== 'http')
  .map(article => article.attributes.url)

writeFileSync(`${__dirname}/../.prerenderrc`, JSON.stringify(routes))
```
`articles.js` exports an array of front-matter-parsed articles & menu-items with defaults in `attributes.url`.

my `package.json` has this:

```json
{
  "scripts": {
    "build": "rimraf dist && parcel build src/index.html",
    "prebuild": "rimraf .prerenderrc && parcel build --target=node --no-source-maps src/prerender.js && node dist/prerender.js",
  }
}
```

This works fine, but it'd be neat if it was integrated so I didn't need the `prebuild`

**Comment by ABuffSeagull** [comment]
Oh, since this uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), you should be able to just make a `prerender.config.js` like this:
```js
const articles = require("./articles");

module.exports = {
  routes: articles
    .filter(article => article.attributes.url.slice(0, 4) !== 'http')
    .map(article => article.attributes.url)
}
```
(I don't believe it supports ES Modules yet)
