### ISSUE TITLE
[Question] Is there any way to run some js only during prerendering?

### ISSUE THREAD

**Issue by ymatuhin** [ABuffSeagull/parcel-plugin-prerender#24]
For example I want to change some text on website, but I want it only when I prerender content and not run it in a runtime again.

**Comment by ABuffSeagull** [comment]
Just glancing over some of the packages, I'm not sure if there currently is a way with `@prerenderer/prerenderer` as it is.
I'll have to do some testing to see if you can fire events from Puppeteer before rendering.
