### ISSUE TITLE
Fails when --public-url is set

### ISSUE THREAD

**Issue by lukechilds** [ABuffSeagull/parcel-plugin-prerender#7]
If `--public-url https://example.com` is set so URLs use absolute paths (a requirement for og:image) then pre-rendering can't load any resources.

Or if the sites already published it will load the (old) live resources not the local resources.

**Comment by lukechilds** [comment]
@ABuffSeagull what do you think the likelihood of getting this working is?

I'm not really sure it's possible without doing some crazy hacks.

One idea I had would be running a local server and serving the `dist` directory, then running a proxy server proxying `--public-url` to the local server. Then we could get the puppeteer Chromium instance to use the proxy.

That should work but it's pretty messy. Do you have any better ideas?

**Comment by lukechilds** [comment]
Actually that would then break if they're making any requests to `--public-url` that aren't static.

e.g `https://example.com/api/foo` will now get proxied to our local server and fail.

I'm starting to think there just isn't a solution to this.

If you want local prerendering you need to use relative URLs.

**Comment by ABuffSeagull** [comment]
I will have to admit, it took me quite a while to really understand what you're talking about :laughing:. But yeah, I don't think there's a way you can have both a dynamic request at prerender time, and `--public-url` set.
The only way I think it could work is if you have your frontend and backend on different hostnames (e.g. `https://example.com` and `https://api.example.com`), but obviously that's a pretty specific use case.

**Comment by lukechilds** [comment]
Yeah I think it's probably best to close this issue.

Unfortunately absolute URLs are required for og:image tags.  I don't think you can specify an absolute URL for only certain assets with parcel.

I could write a separate plugin that parses HTML for og:image tags and sets an absolute source but that's not a great solution.

**Comment by lukechilds** [comment]
@ABuffSeagull fixed this rather crudely with this plugin: https://github.com/lukechilds/parcel-plugin-ogimage

**Comment by ABuffSeagull** [comment]
I mean hey, whatever gets the job done :smile:
